import assert from "node:assert/strict";
import test from "node:test";
import { EventEmitter } from "node:events";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { SETUP_UUID, SetupService, diagnosticCode, diagnosticResult } from "../plugin/setup.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const ACTION_ID="11111111-1111-4111-8111-111111111111";
function runtime(){const handlers={},renders=[],toasts=[],launches=[],pi=[],settings=[];const client={onAdd(f){handlers.add=f;return this},onRun(f){handlers.run=f;return this},onSendToPlugin(f){handlers.message=f;return this},onParamFromPlugin(f){handlers.param=f;return this},onDidReceiveSettings(f){handlers.settings=f;return this},onClear(f){handlers.clear=f;return this},decodeContext(c){const[uuid,key,actionid]=c.split("___");return{uuid,key,actionid}},setBaseDataIcon(c,d,text){renders.push({c,d,text})},sendToPropertyInspector(payload,context){pi.push({payload,context})},setSettings(value,context){settings.push({value,context})},toast(m){toasts.push(m)}};const launcher=(args)=>{const child=new EventEmitter();child.unref=()=>{child.unreferenced=true};launches.push({args,child});return child};return{handlers,renders,toasts,launches,pi,settings,client,launcher}}

test("setup action is a second ordinary Keypad action with packaged assistant",()=>{const manifest=JSON.parse(readFileSync(join(root,"manifest.json"),"utf8"));assert.equal(manifest.Actions.length,2);const setup=manifest.Actions.find(a=>a.UUID===SETUP_UUID);assert.ok(setup);assert.deepEqual(setup.Controllers,["Keypad"]);assert.equal(setup.PropertyInspectorPath,"property-inspector/setup.html");for(const file of ["Start-ImageSlideSetup.ps1","Invoke-ImageSlideSetup.ps1","Apply-ImageSlideSetup.cmd","compatibility.json","receipt-template.json"])assert.ok(readFileSync(join(root,"helper",file)).length>0);const helper=readFileSync(join(root,"helper","Invoke-ImageSlideSetup.ps1"),"utf8"),bootstrap=readFileSync(join(root,"helper","Start-ImageSlideSetup.ps1"),"utf8");assert.match(helper,/ValidateSet\('Assistant','Prepare','Apply'\)/);assert.match(helper,/while\(StudioRunning\)/);assert.match(helper,/-Mode Apply/);assert.match(bootstrap,/Start-Process/);assert.match(bootstrap,/-Mode Assistant/)});

test("setup routes only normal keys and launches the detached-assistant bootstrap",()=>{const r=runtime(),service=new SetupService({client:r.client,root,platform:"win32",launcher:r.launcher,localAppData:""});service.bind();const good=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context:good});r.handlers.run({uuid:SETUP_UUID,context:`${SETUP_UUID}___3_2___${ACTION_ID}`});assert.equal(r.launches.length,0);r.handlers.run({uuid:SETUP_UUID,context:good});assert.equal(r.launches.length,1);assert.deepEqual(r.launches[0].args.slice(-4),["-PressedKey","0_0","-SetupActionId",ACTION_ID]);assert.match(r.launches[0].args[r.launches[0].args.indexOf("-File")+1],/Start-ImageSlideSetup\.ps1$/);assert.deepEqual(r.launches[0].args.slice(r.launches[0].args.indexOf("-Operation"),r.launches[0].args.indexOf("-Operation")+2),["-Operation","install"]);assert.equal(r.launches[0].child.unreferenced,true);assert.match(r.toasts[0],/Close Studio/);assert.equal(service.last.status,"launching")});

test("setup failure and non-Windows operation fail closed",()=>{const r=runtime();const service=new SetupService({client:r.client,root,platform:"linux",launcher:r.launcher});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});r.handlers.run({uuid:SETUP_UUID,context});assert.equal(r.launches.length,0);assert.match(r.toasts[0],/Windows/)});

test("Property Inspector operation is persisted, validated, and locked while running",()=>{const r=runtime();const service=new SetupService({client:r.client,root,platform:"win32",launcher:r.launcher,localAppData:""});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});r.handlers.message({uuid:SETUP_UUID,context,payload:{type:"updateSetupOperation",operation:"restore"}});r.handlers.message({uuid:SETUP_UUID,context,payload:{type:"updateSetupOperation",operation:"invalid"}});assert.deepEqual(r.settings,[{value:{operation:"restore"},context}]);r.handlers.run({uuid:SETUP_UUID,context});r.handlers.message({uuid:SETUP_UUID,context,payload:{type:"updateSetupOperation",operation:"repair"}});const index=r.launches[0].args.indexOf("-Operation");assert.deepEqual(r.launches[0].args.slice(index,index+2),["-Operation","restore"]);assert.equal(r.settings.length,1);assert.equal(r.pi.at(-1).payload.operation,"restore")});

test("Property Inspector can request persisted bounded status",()=>{const r=runtime();const record=JSON.stringify({status:"failed",code:"PROFILE_NOT_FOUND",phase:"DEVICE_PROFILE_MATCH",category:"SCHEMA",ignoredPath:"C:\\Users\\secret"});const service=new SetupService({client:r.client,root,platform:"win32",launcher:r.launcher,localAppData:"C:\\Local",readDiagnostic:()=>record});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.message({uuid:SETUP_UUID,context,payload:{type:"requestSetupState"}});assert.deepEqual(r.pi.at(-1).payload,{type:"setupStatus",status:"failed",code:"PROFILE_NOT_FOUND",phase:"DEVICE_PROFILE_MATCH",operation:"install"})});

function persistedFixture(overrides={}){const local="C:\\Local";const request={schema:"com.arkamax.ulanzi.imageslide.setup-request/v5",pluginVersion:"0.2.0",expiresUtc:new Date(Date.now()+60000).toISOString(),setupKey:"0_0",setupActionIdSha256:createHash("sha256").update(ACTION_ID.toLowerCase()).digest("hex"),...overrides};const json=JSON.stringify(request),digest=createHash("sha256").update(json).digest("hex"),file="a".repeat(32)+".json";const files=new Map([[join(local,"Arkamax","ImageSlidePlugin","last-diagnostic.json"),JSON.stringify({status:"prepared",code:"PREPARED",phase:"REQUEST_WRITE"})],[join(local,"Arkamax","ImageSlidePlugin","requests","current.json"),JSON.stringify({schema:"com.arkamax.ulanzi.imageslide.request-pointer/v1",file,sha256:digest})],[join(local,"Arkamax","ImageSlidePlugin","requests",file),json],[join(local,"Arkamax","ImageSlidePlugin","requests",file+".sha256"),digest]]);return{local,files,readText:path=>{if(!files.has(path))throw Error("missing");return files.get(path)}}}

test("PREPARED restoration requires a current request bound to this Setup instance",()=>{const f=persistedFixture(),r=runtime(),service=new SetupService({client:r.client,root,localAppData:f.local,readText:f.readText});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});assert.equal(service.last.status,"waiting");assert.equal(service.last.code,"PREPARED")});

test("stale success is not reported as installed unless the bound live center is Image Slideshow",()=>{const f=persistedFixture({manifestPath:"C:\\Profiles\\page\\manifest.json",expiresUtc:new Date(Date.now()-1000).toISOString()}),r=runtime();f.files.set(join(f.local,"Arkamax","ImageSlidePlugin","last-diagnostic.json"),JSON.stringify({status:"success",code:"SUCCESS",phase:"RELAUNCH"}));f.files.set("C:\\Profiles\\page\\manifest.json",JSON.stringify({Controllers:[{Type:"Keypad",Actions:{"0_0":{Action:SETUP_UUID,ActionID:ACTION_ID},"3_2":{Action:"com.ulanzi.ulanzideck.smallwindow.window"}}}]}));const service=new SetupService({client:r.client,root,localAppData:f.local,readText:f.readText});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});assert.equal(service.last.status,"ready");f.files.set("C:\\Profiles\\page\\manifest.json",JSON.stringify({Controllers:[{Type:"Keypad",Actions:{"0_0":{Action:SETUP_UUID,ActionID:ACTION_ID},"3_2":{Action:"com.arkamax.ulanzi.imageslide.slideshow"}}}]}));r.handlers.message({uuid:SETUP_UUID,context,payload:{type:"requestSetupState"}});assert.equal(service.last.status,"installed")});

test("legacy terminal diagnostics cannot claim the current page is installed",()=>{const f=persistedFixture({schema:"com.arkamax.ulanzi.imageslide.setup-request/v4",pluginVersion:"0.1.9"}),r=runtime();f.files.set(join(f.local,"Arkamax","ImageSlidePlugin","last-diagnostic.json"),JSON.stringify({status:"success",code:"SUCCESS",phase:"RELAUNCH"}));const service=new SetupService({client:r.client,root,localAppData:f.local,readText:f.readText});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});assert.equal(service.last.status,"ready")});

test("stale diagnostic and invalid requests require a new Setup press",()=>{for(const variant of ["missing","old-schema","version","expired","sidecar","binding"]){const f=persistedFixture(variant==="old-schema"?{schema:"com.arkamax.ulanzi.imageslide.setup-request/v3"}:variant==="version"?{pluginVersion:"0.1.7"}:variant==="expired"?{expiresUtc:new Date(Date.now()-1000).toISOString()}:variant==="binding"?{setupActionIdSha256:"0".repeat(64)}:{});if(variant==="missing")f.files.delete(join(f.local,"Arkamax","ImageSlidePlugin","requests","current.json"));if(variant==="sidecar")f.files.set(join(f.local,"Arkamax","ImageSlidePlugin","requests","a".repeat(32)+".json.sha256"),"0".repeat(64));const r=runtime(),service=new SetupService({client:r.client,root,localAppData:f.local,readText:f.readText});service.bind();const context=`${SETUP_UUID}___0_0___${ACTION_ID}`;r.handlers.add({uuid:SETUP_UUID,context});assert.deepEqual(service.last,{status:"failed",code:"REPREPARE_REQUIRED",phase:"APPLY_PRECHECK"},variant);assert.equal(r.renders.at(-1).text,"[REPREPARE_REQUIRED:APPLY_PRECHECK]",variant)}});

test("setup binding rejects argument injection before spawn",()=>{const r=runtime();const service=new SetupService({client:r.client,root,platform:"win32",launcher:r.launcher});service.bind();for(const context of [`${SETUP_UUID}___0_0;calc___${ACTION_ID}`,`${SETUP_UUID}___0_0___${ACTION_ID};calc`,`${SETUP_UUID}___3_2___${ACTION_ID}`])r.handlers.run({uuid:SETUP_UUID,context});assert.equal(r.launches.length,0);assert.equal(r.renders.at(-1).text,"[SETUP_INSTANCE_NOT_FOUND:TARGET_RESOLUTION]")});

test("unknown helper diagnostics collapse without leaking input",()=>{assert.equal(diagnosticCode("host.local C:\\Users\\name"),"HELPER_PROCESS_FAILED");assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:SLOT_UNRELATED:SLOT_VALIDATION:INTEGRITY"),{code:"SLOT_UNRELATED",phase:"SLOT_VALIDATION"});assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:EVIL_CODE:PRIVATE_PATH:BAD"),{code:"HELPER_PROCESS_FAILED",phase:"INITIALIZING"})});

test("compatibility subphases survive bounded parsing",()=>{for(const phase of ["COMPAT_PLUGIN_ROOT","COMPAT_MANIFEST_READ","COMPAT_EXE_PATH","COMPAT_VERSION_READ","COMPAT_HASH_READ","COMPAT_ENV_PATHS"])assert.deepEqual(diagnosticResult(`IMAGESLIDE_DIAGNOSTIC:COMPATIBILITY_UNSUPPORTED:${phase}:IO`),{code:"COMPATIBILITY_UNSUPPORTED",phase})});

test("target ambiguity is surfaced separately from slot validation",()=>{assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:PROFILE_AMBIGUOUS:TARGET_RESOLUTION:AMBIGUITY"),{code:"PROFILE_AMBIGUOUS",phase:"TARGET_RESOLUTION"});assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:SETUP_INSTANCE_NOT_FOUND:TARGET_RESOLUTION:SCHEMA"),{code:"SETUP_INSTANCE_NOT_FOUND",phase:"TARGET_RESOLUTION"});assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:SLOT_UNRELATED:SLOT_VALIDATION:INTEGRITY"),{code:"SLOT_UNRELATED",phase:"SLOT_VALIDATION"})});

test("restore diagnostics remain bounded and allowlisted",()=>{assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:RESTORE_BACKUP_NOT_FOUND:RESTORE_RESOLUTION:INTEGRITY"),{code:"RESTORE_BACKUP_NOT_FOUND",phase:"RESTORE_RESOLUTION"});assert.deepEqual(diagnosticResult("IMAGESLIDE_DIAGNOSTIC:RESTORE_BACKUP_INVALID:RESTORE_WRITE:INTEGRITY"),{code:"RESTORE_BACKUP_INVALID",phase:"RESTORE_WRITE"})});
