/* Protocol 2.1.2 PI bridge. Official contract: selectFolderDialog() sends
   selectdialog {type:'folder'} and onSelectdialog receives message.path. */
(() => {
  "use strict";
  const ACTION_UUID="com.arkamax.ulanzi.imageslide.slideshow";
  const query=new URLSearchParams(location.search);
  const state={uuid:ACTION_UUID,key:query.get("key")||"",actionid:query.get("actionid")||"",settings:{folderPath:"",intervalSeconds:10,loop:true,sort:"name",showDateTime:false,dateTimeOnly:false,dateTimeEverySlides:5,dateTimeDurationSeconds:5,dateFormat:"system",showWeather:false,weatherOnly:false,weatherApiKey:"",weatherLocation:"",weatherUnits:"c",weatherEverySlides:5,weatherDurationSeconds:8},socket:null};
  const el=(id)=>document.getElementById(id);
  function send(cmd,fields={}){if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({cmd,uuid:state.uuid,key:state.key,actionid:state.actionid,...fields}));}
  function sendToPlugin(payload){send("sendToPlugin",{payload});}
  function getGlobalSettings(){send("getGlobalSettings");}
  function selectFolderDialog(){send("selectdialog",{type:"folder"});}
  function onSelectdialog(message){if(typeof message.path==="string"&&message.path){state.settings.folderPath=message.path;paintSettings();save();}}
  function paintSettings(){el("folder").value=state.settings.folderPath||"";el("interval").value=state.settings.intervalSeconds;el("loop").checked=state.settings.loop;el("sort").value=state.settings.sort;el("date-time-only").checked=state.settings.dateTimeOnly;el("show-date-time").checked=state.settings.showDateTime;el("date-time-every").value=state.settings.dateTimeEverySlides;el("date-time-duration").value=state.settings.dateTimeDurationSeconds;el("date-format").value=state.settings.dateFormat;el("date-time-schedule").hidden=!state.settings.showDateTime||state.settings.dateTimeOnly||state.settings.weatherOnly;el("date-format-options").hidden=(!state.settings.showDateTime&&!state.settings.dateTimeOnly)||state.settings.weatherOnly;el("weather-only").checked=state.settings.weatherOnly;el("show-weather").checked=state.settings.showWeather;el("weather-api-key").value=state.settings.weatherApiKey||"";el("weather-location").value=state.settings.weatherLocation||"";el("weather-units").value=state.settings.weatherUnits;el("weather-every").value=state.settings.weatherEverySlides;el("weather-duration").value=state.settings.weatherDurationSeconds;el("weather-config").hidden=!state.settings.showWeather&&!state.settings.weatherOnly;el("weather-schedule").hidden=!state.settings.showWeather||state.settings.weatherOnly||state.settings.dateTimeOnly;}
  function paintStatus(status){const box=el("status");box.className=`status ${status?.level||"warning"}`;box.textContent=status?.message||"Waiting for plugin status…";}
  function paintWeatherStatus(status){const box=el("weather-status");box.className=`status ${status?.level||"warning"}`;box.textContent=status?.message||"Weather is disabled.";}
  function save(){const intervalSeconds=Number(el("interval").value),dateTimeEverySlides=Number(el("date-time-every").value),dateTimeDurationSeconds=Number(el("date-time-duration").value),weatherEverySlides=Number(el("weather-every").value),weatherDurationSeconds=Number(el("weather-duration").value);if(!Number.isFinite(intervalSeconds)||intervalSeconds<5){paintStatus({level:"error",message:"Interval must be at least 5 seconds."});return;}if(!Number.isInteger(dateTimeEverySlides)||dateTimeEverySlides<1||!Number.isInteger(dateTimeDurationSeconds)||dateTimeDurationSeconds<1||!Number.isInteger(weatherEverySlides)||weatherEverySlides<1||!Number.isInteger(weatherDurationSeconds)||weatherDurationSeconds<1){paintStatus({level:"error",message:"Frequencies and durations must be positive whole numbers."});return;}state.settings={folderPath:state.settings.folderPath,intervalSeconds,loop:el("loop").checked,sort:el("sort").value,dateTimeOnly:el("date-time-only").checked,showDateTime:el("show-date-time").checked,dateTimeEverySlides,dateTimeDurationSeconds,dateFormat:el("date-format").value,weatherOnly:el("weather-only").checked,showWeather:el("show-weather").checked,weatherApiKey:el("weather-api-key").value,weatherLocation:el("weather-location").value,weatherUnits:el("weather-units").value,weatherEverySlides,weatherDurationSeconds};paintSettings();sendToPlugin({type:"updateSettings",settings:state.settings});}
  function receive(event){let message;try{message=JSON.parse(String(event.data));}catch{return;}if(message.key)state.key=message.key;if(message.actionid)state.actionid=message.actionid;if(message.cmd==="selectdialog")onSelectdialog(message);if(message.cmd==="didReceiveGlobalSettings"&&message.settings){state.settings={...state.settings,...message.settings};paintSettings();}if(message.cmd==="sendToPropertyInspector"&&message.payload){if(message.payload.settings){state.settings={...state.settings,...message.payload.settings};paintSettings();}paintStatus(message.payload.status);paintWeatherStatus(message.payload.weatherStatus);}}
  el("select").addEventListener("click",selectFolderDialog);el("refresh").addEventListener("click",()=>sendToPlugin({type:"refresh"}));el("refresh-weather").addEventListener("click",()=>sendToPlugin({type:"refreshWeather"}));
  el("date-time-only").addEventListener("change",()=>{if(el("date-time-only").checked)el("weather-only").checked=false;save()});el("weather-only").addEventListener("change",()=>{if(el("weather-only").checked)el("date-time-only").checked=false;save()});
  for(const id of ["interval","loop","sort","show-date-time","date-time-every","date-time-duration","date-format","show-weather","weather-api-key","weather-location","weather-units","weather-every","weather-duration"])el(id).addEventListener("change",save);
  const address=query.get("address")||"127.0.0.1",port=query.get("port")||"3906";
  state.socket=new WebSocket(`ws://${address}:${port}`);state.socket.addEventListener("message",receive);state.socket.addEventListener("open",()=>{state.socket.send(JSON.stringify({code:0,cmd:"connected",uuid:ACTION_UUID}));getGlobalSettings();sendToPlugin({type:"requestState"});});state.socket.addEventListener("close",()=>paintStatus({level:"error",message:"Disconnected from Ulanzi Studio."}));state.socket.addEventListener("error",()=>paintStatus({level:"error",message:"Unable to connect to Ulanzi Studio."}));
  paintSettings();paintWeatherStatus();
})();
